version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: taskapp
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 5s
      timeout: 5s
      retries: 5

    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql



  backend:
    build: ./backend
    container_name: taskapp_backend
    restart: always
    depends_on:
      - db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_USER=admin
      - DB_PASSWORD=password123
      - DB_NAME=taskapp
      - DB_PORT=5432
    ports:
      - "3002:3002"


  frontend:
    build: ./frontend
    container_name: taskapp_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3001:3001"

volumes:
  db_data: